config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :shows do
    get 'delete'
    get 'add'
    resources :comments, except: [:index, :show] do
      get 'delete'
    end
  end
  root 'shows#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
  validates :title, presence: true
  validates :plot, presence: true

  has_and_belongs_to_many :users
  has_many :comments, dependent: :destroy

  has_attached_file :poster, styles: {
    tiny: '77x111>',
    thumb: '155x222>',
    medium: '310x444>'
  }

  validates_attachment_content_type :poster, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :poster, :less_than => 4.megabytes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :shows
  has_many :comments, dependent: :destroy

  has_attached_file :avatar, styles: {
    tiny: '32x32>',
    thumb: '64x64>',
    medium: '128x128>'
  }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :less_than => 4.megabytes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  skip_before_filter :verify_authenticity_token

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def delete
    @show = Show.find(params[:show_id])
    @comment = Comment.find(params[:comment_id])
  end

  def create
    @comment = Comment.create(comment_params)

    @comment = Comment.new
    @my_shows = current_user.shows
    @show = Show.find(params[:show_id])
    @comments = @show.comments
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update_attributes(show_params) if @comment.user == current_user

    @my_shows = current_user.shows
    @show = Show.find(params[:show_id])
    @comments = @show.comments
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user || (current_user && current_user.admin)
      @comment.destroy
    else
      @notice = "You can't delete someone else's comment."
    end

    @comment = Comment.new
    @my_shows = current_user.shows
    @show = Show.find(params[:show_id])
    @comments = @show.comments
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id, :show_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :authenticate_user!
  skip_before_filter :verify_authenticity_token

  def index
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
  end

  def show
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comment = Comment.new

    @show = Show.find(params[:id])
    @comments = @show.comments.order("created_at ASC")
  end

  def new
    @show = Show.new
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
  end

  def edit
    @show = Show.find(params[:id])
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comments = @show.comments.order("created_at ASC")
    @comment = Comment.new
  end

  def create
    @show = Show.create(show_params)
    @show.users << current_user
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comments = @show.comments.order("created_at ASC")
    @comment = Comment.new
  end

  def update
    @show = Show.find(params[:id])
    @show.update_attributes(show_params)
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comments = @show.comments.order("created_at ASC")
    @comment = Comment.new
  end

  def delete
    @show = Show.find(params[:show_id])
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comments = @show.comments.order("created_at ASC")
    @comment = Comment.new
  end

  def destroy
    @show = Show.find(params[:id])
    @show.users.delete(current_user)
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comments = @show.comments.order("created_at ASC")
    @comment = Comment.new
  end

  def add
    @show = Show.find(params[:show_id])
    @show.users << current_user
    @my_shows = current_user.shows.order("title ASC")
    @other_shows = Show.all.order("title ASC") - current_user.shows
    @comments = @show.comments.order("created_at ASC")
    @comment = Comment.new
  end

  private
  def show_params
    params.require(:show).permit(:title, :plot, :poster)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/comments/_delete.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Delete Comment</h3>
        </div>
        <div class="modal-body">
            <ul class="errors"></ul>
            Are you sure you wish to delete your comment ?<br>
            <div class="well"><%= @comment.comment %></div>
        </div>
        <div class="modal-footer">
            <%= link_to "Yes, delete this comment", show_comment_path({show_id: @show.id, id: @comment.id}), method: :delete, remote: true, class: "btn btn-danger" %>
            <%= link_to "No, please don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment, url: show_comments_path(@show), remote: true, html: { style: "display:inline;" } do |f| %>
    <ul class="errors"></ul>

    <div class="form-group">
        <%= f.label :comment, "Your comment", class:"control-label", required: true %>
        <% if !current_user.shows.exists?(@show) %>
        <%= f.text_area :comment, class: "form-control", disabled: true, value: "You can't comment a TV show which is not in your shows.", required: true %>
    </div>
        <% else %>
        <%= f.text_area :comment, class: "form-control", required: true, value: "" %>
        <%= f.number_field :user_id, type: "hidden", value: current_user.id %>
        <%= f.number_field :show_id, type: "hidden", value: @show.id %>
    </div>
  <%= f.submit class: "btn btn-primary" %>
        <% end %>
<% end %>

app/views/comments/_index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Comments</h3>
    </div>
    <div class="panel-body">
      <div id="comment-notice">
        <%= @notice %>
      </div>
      <% if @comments.empty? %>
        <p>No comments yet... :(</p>
      <% end %>
      <% @comments.each do |comment| %>
        <div class="comment">
          <div class="well">
            <% if comment.user == current_user || (current_user && current_user.admin) %>
              <%= link_to show_comment_delete_path(@show, comment), remote: true, class: "close" do %>
                <span aria-hidden="true">&times;</span>
              <% end %>
            <% end %>
            <div class="comment-content">
              <div class="comment-avatar">
                <% if comment.user.avatar.file? %>
                <%= image_tag comment.user.avatar.url(:thumb), alt: comment.user.first_name + " " + comment.user.last_name + "'s avatar" %>
                <% else %>
                <%= image_tag "https://s3-eu-west-1.amazonaws.com/tvshowsonrails/user.svg", class: "default-avatar-comment" %>
                <% end %>
              </div>
              <div class="comment-txt">
                <p><%= comment.comment %></p>
              </div>
            </div>
            <div class="comment-footer">
              <p><i>a dit <%= comment.user.first_name + " " + comment.user.last_name %>, le <%= comment.created_at.strftime("%-d/%-m/%Y à %Hh%M") %> :</i></p>
            </div>
          </div>
        </div>
      <% end %>
      <hr>
      <div class="comment-form">
        <%= render 'comments/form' %>
      </div>
    </div>
</div>

app/views/comments/_save.js.erb
$("ul.errors").html("");
<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $(".comment-list").html("<%= escape_javascript(render 'index') %>");
  $("#comment-modal").modal("hide");
<% end %>

app/views/comments/create.js.erb
<%= render "save" %>

app/views/comments/delete.js.erb
$("#comment-modal").html("<%= escape_javascript(render 'delete') %>")
$("#comment-modal").modal("show")

app/views/comments/destroy.js.erb
<%= render "save" %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVShowsOnRails</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= favicon_link_tag('icons/apple-icon-57x57.png', sizes: '57x57', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-72x72.png', sizes: '72x72', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-60x60.png', sizes: '60x60', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-76x76.png', sizes: '76x76', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-114x114.png', sizes: '114x114', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-120x120.png', sizes: '120x120', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-144x144.png', sizes: '144x144', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-152x152.png', sizes: '152x152', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/apple-icon-180x180.png', sizes: '180x180', rel: 'apple-touch-icon') %>
    <%= favicon_link_tag('icons/android-icon-192x192.png', sizes: '192x192', rel: 'icon', type: 'image/png') %>
    <%= favicon_link_tag('icons/favicon-32x32.png', sizes: '32x32', rel: 'icon', type: 'image/png') %>
    <%= favicon_link_tag('icons/favicon-96x96.png', sizes: '96x96', rel: 'icon', type: 'image/png') %>
    <%= favicon_link_tag('icons/favicon-16x16.png', sizes: '16x16', rel: 'icon', type: 'image/png') %>
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrap">
      <header class="navbar navbar-inverse">
        <div class="container">
          <%= link_to "TVShowsOnRails", root_path, class: "navbar-brand" %>
          <% if user_signed_in? %>
          <div id="navbar navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Shows", root_path %></li>
              <% if current_user.admin %>
              <li><%= link_to "Admin", rails_admin_path %></li>
              <% end %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <li id="connected-as">Connected as<%= link_to current_user.first_name + " " + current_user.last_name + " (" + current_user.email + ")", edit_user_registration_path(current_user) %></li>
              <li id="avatar-header">
                <% if current_user.avatar.file? %>
                <%= link_to image_tag(current_user.avatar.url(:tiny), id: "custom-avatar"), edit_user_registration_path(current_user) %>
                <% else %>
                <%= link_to image_tag("https://s3-eu-west-1.amazonaws.com/tvshowsonrails/user.svg"), edit_user_registration_path(current_user) %>
                <% end %>
              </li>
            </ul>
          </div>
          <% end %>
        </div>
      </header>
      <section>
        <div class="container">
          <div id="notice">
            <%= notice %>
          </div>
          <%= yield %>
        </div>
      </section>
    </div>
    <footer id="footer">
      <div class="container">
        <p>Developed by Sébastien Gaya</p>
        <a id="github-link" href="https://github.com/SebouChu/TVShowsOnRails"></a>
      </div>
    </footer>
  </body>
</html>

app/views/shows/_delete.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">New TV Show</h3>
        </div>
        <div class="modal-body">
            <ul class="errors"></ul>
            Are you sure you wish to delete
            <b><%= @show.title %></b>?
        </div>
        <div class="modal-footer">
            <%= link_to "Yes, delete this show", show_path(@show), method: :delete, remote: true, class: "btn btn-danger" %>
            <%= link_to "No, please don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
        </div>
    </div>
</div>

app/views/shows/_edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">Editing <%= @show.title %></h3>
        </div>
        <%= render "form" %>

app/views/shows/_form.html.erb
<%= form_for @show, remote: true, html: { style: "display:inline;", multipart: true } do |f| %>
<div class="modal-body">
    <ul class="errors"></ul>

    <div class="form-group">
        <%= f.label :title, class:"control-label" %>
        <%= f.text_field :title, class: "form-control", required: true %>
    </div>
    <div class="form-group">
        <%= f.label :plot, class: "control-label" %>
        <%= f.text_area :plot, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= f.label :poster, "Poster", class: "control-label" %>
      <i>(Max. size : 4MB)</i>
        <% if @show.poster.file? %>
        <div class="form-current-pic">
          <%= image_tag @show.poster.url(:tiny) %>
          <div id="aside-poster-form">
            <p>Current poster</p>
          </div>
        </div>
        <% else %>
        <p>No poster yet... :(</p>
        <% end %>
        <%= f.file_field :poster, class: "form-control", onchange: "readURL(this)" %><br>
        <%= image_tag "#", alt: "Poster Preview", id: "img_prev" %>
    </div>
</div>
<div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
</div>
<% end %>
</div>
</div>

app/views/shows/_index.html.erb
<div id="show-notice">
    <%= @show_notice %>
</div>
<h1>My Shows</h1>
<hr class="small-hr">

<% if @my_shows.empty? %>
  <p>Your library is empty. :(</p>
<% end %>
<div class="my-shows">
    <% @my_shows.each do |my_show| %>
    <div class="show-container">
        <div id="poster">
            <% if my_show.poster.file? %>
            <%= image_tag my_show.poster.url(:thumb) %>
            <% else %>
            <%= image_tag "https://s3-eu-west-1.amazonaws.com/tvshowsonrails/no-poster-small.png" %>
            <% end %>
        </div>
        <div id="show-btns">
            <p><%= my_show.title %></p>
            <div id="small-btns">
              <%= link_to edit_show_path(my_show), remote: true do %>
              <%= image_tag "edit.svg", class: "small-btn" %>
              <% end %>
              <%= link_to show_delete_path(my_show), remote: true do %>
              <%= image_tag "delete.svg", class: "small-btn" %>
              <% end %>
            </div>
            <%= link_to "Learn more", show_path(my_show), class: "btn btn-lg btn-success btn-more" %>
        </div>
    </div>
    <% end %>
</div>

<hr id="index-big-hr">

<h1>Other Shows</h1>
<hr class="small-hr">

<% if @other_shows.empty? %>
  <p>You added all the shows ! :D</p>
<% end %>
<div class="other_shows">
    <% @other_shows.each do |other_show| %>
    <div class="show-container">
        <div id="poster">
          <% if other_show.poster.file? %>
          <%= image_tag other_show.poster.url(:thumb) %>
          <% else %>
          <%= image_tag "https://s3-eu-west-1.amazonaws.com/tvshowsonrails/no-poster-small.png" %>
          <% end %>
        </div>
        <div id="show-btns">
            <p><%= other_show.title %></p>
            <div id="small-btns">
              <%= link_to show_add_path(other_show), remote: true do %>
              <%= image_tag "add.svg", class: "small-btn add-btn" %>
              <% end %>
            </div>
            <%= link_to "Learn more", show_path(other_show), class: "btn btn-lg btn-success btn-more" %>
        </div>
    </div>
    <% end %>
</div>

app/views/shows/_new.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title">New TV Show</h3>
        </div>
        <%= render "form" %>

app/views/shows/_save.js.erb
$("ul.errors").html("");
<% if @show.errors.any? %>
  <% @show.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $(".show-list").html("<%= escape_javascript(render 'index') %>");
  $(".show-show").html("<%= escape_javascript(render 'show') %>");
  $("#show-modal").modal("hide");
<% end %>

app/views/shows/_show.html.erb
<div id="show-content">
  <div id="show-infos">
    <h1><%= @show.title %></h1><hr class="small-hr">
    <p><%= @show.plot %></p><br>
    <div id="show-buttons">
      <% if @my_shows.include?(@show) %>
      <%= link_to "Edit", edit_show_path(@show), remote: true, class: "btn btn-lg btn-warning new-btn" %>
      <%= link_to "Delete", show_delete_path(@show), remote: true, class: "btn btn-lg btn-danger new-btn" %>
      <% else %>
      <%= link_to "Add", show_add_path(@show), remote: true, class: "btn btn-lg btn-primary new-btn" %>
      <% end %>
    </div>
  </div>
  <div id="show-poster">
    <% if @show.poster.exists? %>
    <%= image_tag @show.poster.url(:medium) %>
    <% else %>
    <%= image_tag "https://s3-eu-west-1.amazonaws.com/tvshowsonrails/no-poster.png" %>
    <% end %>
  </div>
</div>
<div class="comment-list">
  <%= render 'comments/index' %>
</div>

<%= link_to "Back to Home", root_path, class: "btn btn-lg btn-primary" %>

app/views/shows/add.js.erb
<%= render 'save' %>

app/views/shows/delete.js.erb
$("#show-modal").html("<%= escape_javascript(render 'delete') %>")
$("#show-modal").modal("show")

app/views/shows/edit.js.erb
$("#show-modal").html("<%= escape_javascript(render 'edit') %>")
$("#show-modal").modal("show")

app/views/shows/index.html.erb
<%= link_to "Add a TV show", new_show_path, remote: true, class: "btn btn-lg btn-primary new-btn" %>
<div class="new-show"></div>
<div id="ajaxed-div">
</div>
<div class="show-list">
  <%= render 'index' %>
</div>
<div id="show-modal" class="modal fade"></div>

app/views/shows/new.js.erb
$("#show-modal").html("<%= escape_javascript(render 'new') %>");
$("#show-modal").modal("show");

app/views/shows/show.html.erb
<div class="show-show">
  <%= render 'show' %>
</div>
<div id="show-modal" class="modal fade"></div>
<div id="comment-modal" class="modal fade"></div>

app/views/shows/update.js.erb
<%= render "save" %>